name = "xero-invoice-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"
account_id = "442567af9f9ae4f948e8310c20266185"

[vars]
FRONTEND_URL = "https://xero-app.pages.dev"

# Set these as secrets via: wrangler secret put XERO_CLIENT_ID, etc.
# XERO_CLIENT_ID
# XERO_CLIENT_SECRET

[[kv_namespaces]]
binding = "TOKENS"
id = "4ee8d62f5e0e41cdb698edbee40a79cb"
